[package]
name = "amane-shell"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "amane-shell"
path = '/home/mystiafin/.config/amane/src/main.rs'

[dependencies]
amane = { path = '/home/mystiafin/.cache/amane/library' }

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
opt-level = 3
debug = false
incremental = false

[workspace]
